# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField(default=0)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Any')], null=True)),
                ('deposit', models.IntegerField(default=0)),
                ('num_of_rooms', models.IntegerField(default=0)),
                ('amenities', models.TextField(blank=True)),
                ('fbid', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default', max_length=100)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='Geniebot.Location'),
        ),
    ]
