# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geniebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
